server:
  port: 8083

spring:
  application:
    name: app-iot
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: @nacos.server-addr@
        namespace: @nacos.namespace@
      config:
        server-addr: @nacos.server-addr@
        namespace: @nacos.namespace@
  config:
    import:
      - optional:nacos:datasource.yaml
      - optional:nacos:common.yaml
