server:
  port: 8081

spring:
  application:
    name: maku-cloud-system
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: @nacos.server-addr@
        namespace: @nacos.namespace@
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - optional:nacos:datasource.yaml
      - optional:nacos:common.yaml
  mqtt:
    host: tcp://117.72.93.22:1883
    username: admin
    password: public
    clientId: springboot-server8888
    default-topic: iot/device/#

storage:
  enabled: true
  config:
    # 存储类型：local、aliyun、tencent、qiniu、huawei、minio
    type: minio
  minio:
    access-key: xxx
    secret-key: xxx
    end-point: http://117.72.93.22:9000
    bucket-name: yyy-se

